### ISSUE TITLE
depends in rapid games don't work

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#13]
why was "Spring Features v1.9" as depend added?

this seems to not work!

**Comment by ForbodingAngel** [comment]
Depends in rapid games certainly do work. Evo has had that dependency for ages. It's map dependencies that don't work half the time. Ofc, it all works fine in SWL, but you have chosen not to add that functionality in SL (map deps).

And as to why, it's for future compatibility. Additionally, it gives us access to everything in that package (which is a lot).

**Comment by abma** [comment]
ok, i don't care about fixing then when you don't care about stuff working

**Comment by abma** [comment]
and no, they do NOT Work.

**Comment by abma** [comment]
> but you have chosen not to add that functionality in SL (map deps).

thats just a lie.

**Comment by ForbodingAngel** [comment]
@abma , yes. They do work. I don't know how to put this to you any more plainly. It has been a staple in Evo for like 2 years now, and I JUST a few hours go, deleted all pool and packages (and rapid), joined a host, and evo+sf was downloaded. The same thing happens for BA. I don't understand why you are pushing this.

Please, note the time: https://i.imgur.com/sli9P32.png

Additionally, if you're meaning to say that dependencies from rapid packages don't work in general, that's simply false.

> thats just a lie.

If it has never worked properly (and I would know), how is that a lie? If you remember, I was releasing maps with dependencies in them, yes SL _never_ downloaded the dependencies. I also complained about it in the forums as well. The only lobby that properly downloaded map dependencies was SWL. It was never fixed in SL to my knowledge, to the point where I dropped map dependencies entirely from the maps. As a result, without the deps, you get a giant list of missing content errors in infolog.

**Comment by abma** [comment]
> , yes. They do work. I don't know how to put this to you any more plainly. It has been a staple in Evo for like 2 years now, and I JUST a few hours go, deleted all pool and packages (and rapid), joined a host, and evo+sf was downloaded. The same thing happens for BA. I don't understand why you are pushing this.

i'm not sure about this but it looks like depends for rapid was never directly implemented in pr-downloader, so they can't work. also they weren't be used commonly so... in short: currently pr-downloader ba:test doesn't download the dependency

> thats just a lie.

> If it has never worked properly (and I would know <- I say this as someone who was having to deal with people using SL and ZKL having issues with it), how is that a lie? If you remember, I was releasing maps with dependencies in them, yet SL (and ZKL) never downloaded the dependencies.

map depends work probably with pr-downloader. if not, its a bug! (there is no open bug report about this). Its a lie that i have chosen not to add that functionality in SL (map deps). This functionality exists and in pr-downloader and should work!

I don't care about SWL and ZKL: pr-downloader must be the reference and is also used in the engine for downloading stuff. You maybe have noticed that ZK uses spring and possible uses pr-downloader as well. i didn't investigate how they implemented stuff.

**Comment by ForbodingAngel** [comment]
Abma, game dependencies for rapid work perfectly fine: https://i.imgur.com/keaygqz.png

This is ba:test

**Comment by abma** [comment]
how did you download it?

**Comment by ForbodingAngel** [comment]
Joining a host in swl. Works for joining a host in SL as well, although SL seems to sometimes use old PR versions so the rapid package lists don't always update properly? I haven't seen that issue in a long time (was fixed eons ago). SWL grabs latest pr every launch. I'm guessing that SL relies on the one included with the engine (I haven't looked)?

Anyway, both SL and SWL work for grabbing the dep.

**Comment by ForbodingAngel** [comment]
Proof in SL: 
https://i.imgur.com/emvON8M.png
https://i.imgur.com/gyeT0th.png

**Comment by abma** [comment]
$ mkdir /tmp/test
$ src/pr-downloader --filesystem-writepath /tmp/test ba:test
[...]
$ ls /tmp/test/packages/
d63f3d4bfd41c36baaf022c7c3185563.sdp

-> pr-downloader seems to ignore depends + good to know that it works in SL

**Comment by ForbodingAngel** [comment]
So what you've been saying is that pr-downloader itself ignores depends. Well, I knew that, but the lobbies don't. Hence, the lobby sees that it needs X package to sync, it sends command to PR and everyone is happy.

Direct depend support in PR would be excellent though (on a total offtopic sideote, so would make-sdd).
