### ISSUE TITLE
Revert unit cost rounding

### ISSUE THREAD

**Issue by ShoX1988** [Balanced-Annihilation/Balanced-Annihilation#146]
Revert M & E costs to 9.46 values

**Comment by silentwings** [comment]
> Revert M & E costs to 9.46 values
Is this meant literally? Because, presumably, other changes to the numbers besides rounding were made since 9.46.

**Comment by ShoX1988** [comment]
Yeah good point, the only changes outside of the rounding afaik were:
Stumpy/Raider/Bulldog/Reaper: metal cost +5% -seems neglible, don't think it matter either way
Tremor: metal cost -10%, accuracy +15% -keep
Sea cons: cost decreased (ARM: m:273->150, e:25677->7800, CORE: m:271-140, e:25650->8200) -keep
T2 bombers E cost (should actually keep this one, but has no value to revert to as its halfway between what it was before the nerf in 7.92)
Guardian/Punisher: metal cost -16% -keep
Plasma shields: cost -20% -keep

**Comment by silentwings** [comment]
There are many more (non-rounding) changes than that listed in the changelog: https://springrts.com/phpbb/viewtopic.php?f=44&t=38957&start=20#p590068

**Comment by silentwings** [comment]
I also think there are many changes to costs that are not listed in the changelog that was posted on forums - for example https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/6d3fb2852d2ab0708277d74f034ec08b96ee1e43

**Comment by silentwings** [comment]
Having checked a few special cases (eg. armca) I completely bemused by the (many) "rounding" commits, which often seem to have a much bigger effect than any reasonable rounding effort.

For example, armca energy cost, list of changes since 9.46 backwards in time:
4200 (current)
4500
5000 
4608
6000
4600
4608 (9.46 value)

The most recent commit involved here says: 
"Rounded costs closer to original using algorithm, based on values from 9.46" 
which at least in this case is simply not true.

There is no chance of picking through commit log and undoing stuff in the "proper" way, because its a complete mess and often the commit message is a poor/inaccurate description of what was done.

I think there is no reasonable way to do what is asked here other than a full revent of all unit costs to their 9.46 values, following by re-application of any wanted changes. Is that OK to do?

**Comment by PtaQQ** [comment]
Seems a bit weird, as in the sheet we used for calculating the last roundups it is 4500. Dunno  what happ

**Comment by Ruwetuin** [comment]
see changelog  • T1 Aircons: buildpower +10%, energy cost -10%, buildtime -10%

**Comment by silentwings** [comment]
I can see the changelog is correct for armca, yes, however the commit citing that a -10% change is "rounding closer to 9.46 values" is oO

**Comment by Fx-Doo** [comment]
The costs that had been rounded previously have been rounded again with a smaller gap between new vs old values.

The -10% cost initially happened on the rounded value (which was 5000) and not on the BA 9.46 value).
Which resulted in 4608 rounded to 5000 => -10% => 4500.
4500 was further from (4608)*0.9  than 4200 currently is. The sentance is true, you just have to know what "4500" actually was, and what is considered the "goal" value: 9.46 +/- the intended buff/nerfs

**Comment by silentwings** [comment]
ShoXToday at 12:24 AM @Bluestone re: https://github.com/Balanced-Annihilation/Balanced-Annihilation/issues/146#issuecomment-482685680 just revert that second lot you mentioned.

**Comment by silentwings** [comment]
n2s armuwmex coruwmex aren't matched
