### ISSUE TITLE
integrate chickens directly into BA

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#3]
imo it doesn't make much sense to keep it on svn.

**Comment by Ruwetuin** [comment]
true... forb will do it :D also implementing his cleaned independant CD modification.... forb?

**Comment by abma** [comment]
would it make sense to directly integrate it into BA or are there a lot of conflicting gadgets/scripts?

**Comment by ForbodingAngel** [comment]
I will implement it properly from my clean repo. The ba one is an epic mess :-( I used the ba mutator as a base originally (was the closest thing I could find to a clean copy).

I also have implemented a lot of checks for turning it off and on at the proper times. Chickens is badly conceived tbh :-/. I'm trying to make it better though.

**Comment by ForbodingAngel** [comment]
Implementing it directly is the better choice at this stage. Originally, Chickens would constantly run, even if there were no chicken AI present. I implemented a lot of checks to make sure that the relevant parts of chicken properly shut down if there is not a chicken AI present.

Additionally there are many parts of chickens that simply don't work. Melee units in spring just don't work due to the way that collision detection works (for example a unit with a large hitsphere can't be attacked), so I'm working on ways to clean up various problems that I am seeing.
