### ISSUE TITLE
migrate old tickets?

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#5]
there are some BA related bug repots on the old issue tracker:

http://imolarpg.dyndns.org/trac/balatest/query?status=assigned&status=new&status=reopened&component=BA+trunk&col=id&col=summary&col=component&col=status&col=owner&col=type&col=priority&col=changetime&order=priority

will these be migrated / be looked at or...?

**Comment by ForbodingAngel** [comment]
Honestly, no. They're way too out of date at this point.

**Comment by nixtux** [comment]
I disagree there are some valid tickets imo
e.g.
http://imolarpg.dyndns.org/trac/balatest/ticket/1139
http://imolarpg.dyndns.org/trac/balatest/ticket/1136
http://imolarpg.dyndns.org/trac/balatest/ticket/1129
http://imolarpg.dyndns.org/trac/balatest/ticket/1130

The last two are from the spring engine validation something imo that should never be overlooked.

**Comment by ForbodingAngel** [comment]
No.

1139: Can't seem to replicate
1136: Highly situational. Added or 0 to catch exceptions.
1129: Invalid in current BA
1130: Highly situational and invalid due to the fact that that gadget isn't even used anymore.

**Comment by knorker** [comment]
http://imolarpg.dyndns.org/trac/balatest/ticket/1139 does not need to be replicated because the report already contains the lua error message and a replay.

If BA has no active competent maintainers at the moment then it would be better not to let runalong schmos do random decisions that will make it harder in future for others to pick up development. (recent commits and comments are tragic enough)
