### ISSUE TITLE
what happened to weapons/nuclear_explosions.lua

### ISSUE THREAD

**Issue by nixtux** [Balanced-Annihilation/Balanced-Annihilation#6]
[f=-000001] [weapondefs.lua] Error: Missing return table from: weapons/nuclear_explosions.lua

why is file empty ?

**Comment by ForbodingAngel** [comment]
Because it isn't used yet. Initially it was going to be, but it hasn't been used yet.

Please stop making tons of github issues over obvious things that haven't been dealt with yet.

**Comment by nixtux** [comment]
Pardon, I spend the only free time I had tonight reporting issue I've noticed and this is the comment you made thanks a bunch.

**Comment by ForbodingAngel** [comment]
Well look, the only reason I get snippy about it is that you're reporting stuff that happens in infolog every single time we start the game for testing. We are well aware of that. What we want to know about are the things that do not show in infolog. Anyone working with spring will almost always have infolog open on a different monitor checking the input. Most of us know our infologs better than our own families at this point.

By reporting this stuff, it diminishes _real_ bugs that get reported, because those reports are buried in a sea of irrelevance.

As an example... The stuff you reported tonight was known. All of it. None of it caused any actual problems, so it was relegated to getting fixed later when we weren't so busy. But because of these reports, I ended up wasting a bunch of time fixing minor issues that could have waited until I'm not so busy. That makes it very frustrating when we are trying to accomplish a much larger goal.

FWIW, I'm sorry for being so rude. I was rather frustrated at the time.
