### ISSUE TITLE
Commander getting stucked on buildqueues

### ISSUE THREAD

**Issue by Fx-Doo** [Balanced-Annihilation/Balanced-Annihilation#82]
When commander is performing a buildqueue (mostly lines), it sometimes get stucked and refuses to complete its queue unless a move order is performed.

Happens on collision with previously built buildings, when unit_colslows.lua is enabled.

**Comment by Fx-Doo** [comment]
Seems to be related to commanders having "0" as its speed value, and therefor a calculation that divides udef.speed by the instant speed returns NaN.

Seems fixed by adding instantspeed (vw1) =~ 0 condition to the calculation and setting the values to 0 if vw1 == 0.

**Comment by Fx-Doo** [comment]
https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/6d2b9f2 should've fixed this issue, please report any occurence after this commit here.

**Comment by ForbodingAngel** [comment]
Why not just change the function in question to multiplication instead of
division?

On Oct 11, 2017 1:34 PM, "Fx-Doo" <notifications@github.com> wrote:

6d2b9f2
<https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/6d2b9f2>
should've fixed this issue, please report any occurence after this commit
here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Balanced-Annihilation/Balanced-Annihilation/issues/82#issuecomment-335939466>,
or mute the thread

**Comment by Fx-Doo** [comment]
Well, i'd always have to use 1/vw1 at some point, so the issue would remain the same i guess.
Unless i have forgotten some maths magic, which is pretty likely.
