### ISSUE TITLE
Upgrade lisibility

### ISSUE THREAD

**Issue by FabriceFABS** [Balanced-Annihilation/Balanced-Annihilation#85]
I did you Flo a pic.
On 1 line (on bottom of each icon), it will be so better ! Use kilos !

![flo](https://user-images.githubusercontent.com/6024913/32807353-d78fa6aa-c98f-11e7-9a91-e9397a2666b6.png)

**Comment by FabriceFABS** [comment]
Eventually place top-left > Metal cost, and bottom right E cost.

**Comment by ForbodingAngel** [comment]
That's just confusing, moreover, it would obscure the unit in the picture and it makes the user have to visually search for info instead of it being in a logical position from the beginning.

**Comment by triton13** [comment]
I miss buildtime, and when you queue multiple units, it's hard to see difference between the number used for units queued and the metal cost, looks like it's almost same color.
Every time I need to fast disable queue and make something new, I forget a unit I didnt see, and I end up spamming 1 T2 cons + 1 zipper, instead of pure zippers for example.

In this game you have 3 ressources, Metal Energy and Time, who never lost a game after ctrl+a and move all units for example? Last time It happenned to me I lost like 30 sec micro.

Some units and some buildings are very TIME efficient here, like Levelers, and some units needs more time to build than their cost seems to mean.

I would be nice to compare all units/building cost and buildtime. units and buildings with op ratio like levelers would be A, average units and buildings would be B, and very long stuff to build compared to cost would be C? Or something like that.

Maybe the color of the number for amount of units queued could be changed also.

**Comment by triton13** [comment]
+1 for using 1k instead of 1000 like fabs said also

**Comment by Ruwetuin** [comment]
cost is too variable that using 'k' will help enough
